### ISSUE TITLE
NUSBot Notification Center

### ISSUE THREAD

**Issue by kennetham** [nusmodifications/nusbot#1]
Monitors user-set alerts, send notification via Telegram when it is due.
Runs in background and constantly checks for active jobs to notify.

**Comment by kennetham** [comment]
- [v0.3.57] Added `scheduler` to parse duration 5ecb94e5de9c64ba5d723729de0734cc00d5397d
- [v0.3.56] Added `Notifications` to notify users 100b7f710457694ca1efb53caf3bc7bfedc5e466
- [x] Algorithm to send notification
- [x] Algorithm to parse duration
  - [x] Parse s, m, h, d, w, M, y values
- [ ] Real-time monitoring service to read alert jobs from Redis
- [ ] Algorithm to monitor many different schedules from users

**Comment by yangshun** [comment]
@cgcai why you remove this from the milestone?

**Comment by kennetham** [comment]
[v0.3.75] Updated Notifications Controller b1d763cf86acfb5a26d44ccbee0f526001b188d9
[v0.3.74] Fix scheduler with persistence storage 0177ae22dbab5954e481e3caf0afe941c6cea61e
- [x] Algorithm to send notification
- [x] Algorithm to parse duration
  - [x] Parse s, m, h, d, w, M, y values
- [x] Real-time monitoring service to read alert jobs from Redis
- [x] Algorithm to monitor many different schedules from users
